<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="14" time="0.091" timestamp="2022-02-04T11:23:53.843385" hostname="OhziiiLov3-MacBook.local"><testcase classname="tests.test_accum" name="test_accumulator_init" time="0.001" /><testcase classname="tests.test_accum" name="test_accumulator_add_one" time="0.001" /><testcase classname="tests.test_accum" name="test_accumulator_add_three" time="0.001" /><testcase classname="tests.test_accum" name="test_accumulator_add_twice" time="0.001" /><testcase classname="tests.test_accum" name="test_accumulator_cannot_set_count_directly" time="0.001" /><testcase classname="tests.test_math" name="test_one_plus" time="0.001"><failure message="assert (1 + 1) == 0">def test_one_plus():
        # assert is bulit-in and evaluates as a boolean and raises an excpetion of type error
&gt;       assert 1 + 1 == 0
E       assert (1 + 1) == 0

tests/test_math.py:14: AssertionError</failure></testcase><testcase classname="tests.test_math" name="test_one_plus_two" time="0.001" /><testcase classname="tests.test_math" name="test_divide_by_zero" time="0.001" /><testcase classname="tests.test_math" name="test_multiplication[2-3-6]" time="0.001" /><testcase classname="tests.test_math" name="test_multiplication[1-99-99]" time="0.001" /><testcase classname="tests.test_math" name="test_multiplication[0-99-0]" time="0.001" /><testcase classname="tests.test_math" name="test_multiplication[3--4--12]" time="0.001" /><testcase classname="tests.test_math" name="test_multiplication[-5--5-25]" time="0.001" /><testcase classname="tests.test_math" name="test_multiplication[2.5-6.7-16.75]" time="0.001" /></testsuite></testsuites>